# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: wconnell <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/11/01 21:22:58 by wconnell          #+#    #+#              #
#    Updated: 2018/11/01 21:27:40 by wconnell         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = ft_display_file

SR = ft_display_file.c

all: $(NAME)

$(NAME):
	gcc -Wall -Wextra -Werror -o $(NAME) $(SR)

clean:
	rm -f $(NAME)

fclean: clean
	rm -f $(NAME)

re: fclean all
